name: Releases

on:
  push:
    branches:
      - "master"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,site/assets/files/1019/*.json"
#          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}

